# Example of COVID data analysis

In [1]:
import pandas as pd
import numpy as np
import igraph as ig
from PathNet import *

pos = pd.read_csv('/home/keyan/phynn/knowledge_informed_ml/data/data_processed/pos_processed.csv', index_col=0)
neg = pd.read_csv('/home/keyan/phynn/knowledge_informed_ml/data/data_processed/neg_processed.csv', index_col=0)

pos_adductlist = ["M+H","M+NH4","M+Na","M+ACN+H","M+ACN+Na","M+2ACN+H","2M+H","2M+Na","2M+ACN+H"]
neg_adductlist = ["M-H", "M-2H", "M-2H+Na", "M-2H+K", "M-2H+NH4", "M-H2O-H", "M-H+Cl", "M+Cl", "M+2Cl"]

In [2]:
pos

,m.z,time,min.mz,max.mz,B1_WU350.004_d7_polar_pos.mzML,B1_WU350.005_d14_polar_pos.mzML,B1_WU350.005_d7_polar_pos.mzML,B1_WU350.006_d14_polar_pos.mzML,B1_WU350.006_d3_polar_pos.mzML,B1_WU350.006_d7_polar_pos.mzML,...,B9_WU350.394_d7_polar_pos.mzML,B9_WU350.395_d0_polar_pos.mzML,B9_WU350.397_d0_polar_pos.mzML,B9_WU350.397_d3_polar_pos.mzML,B9_WU350.397_d7_polar_pos.mzML,B9_WU350.398_d0_polar_pos.mzML,B9_WU350.398_d3_polar_pos.mzML,B9_WU350.398_d7_polar_pos.mzML,B9_WU350.400_d0_polar_pos.mzML,B9_WU350.400_d3_polar_pos.mzML
result.1,52.005422,418.545572,52.005384,52.005482,85530.001183,55716.927932,78463.783905,87818.823468,83335.367808,69348.930247,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
result.2,54.033476,93.617746,54.033242,54.033630,35052.291410,17904.639169,34400.610317,31647.902880,19537.655981,28326.013992,...,12174.912853,34223.796050,14463.007116,4972.732006,13766.228865,35769.269770,13691.647408,17972.398949,79811.587314,10065.422182
result.3,55.017475,146.695128,55.017313,55.017553,34644.354458,88735.159057,134745.011778,16375.625602,11495.036903,32672.231626,...,116412.430610,0.000000,48732.303279,41801.556677,3464.202603,10417.316458,39948.806477,52959.669185,43728.046183,45710.455393
result.4,55.053901,323.240583,55.053743,55.054051,16964.458620,26120.433664,42378.503321,33170.442395,1647.132920,9065.605728,...,146451.826127,13157.735513,18156.421585,25205.035827,62393.841232,20323.284498,27358.008688,62016.503103,27638.428631,18423.519010
result.5,56.049186,309.560707,56.049126,56.049269,62445.959035,264399.696582,295093.067672,359781.325464,77004.536321,139536.055256,...,335054.938858,237307.384464,125196.469977,209823.110488,302240.064327,136977.018443,180106.408567,195507.262786,186028.533651,118751.512063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
result.4684,1428.219728,513.455827,1428.219099,1428.220357,40071.643984,32831.231610,36937.302413,30940.829917,35533.822435,30879.457646,...,18028.246814,23578.454739,19208.231755,18907.557534,30498.255144,21457.588997,15265.572366,9733.044909,11932.747080,20921.726089
result.4685,1452.679091,601.251092,1452.678723,1452.679885,110194.944987,56198.918084,62376.145129,67750.193595,100256.422686,64799.363783,...,128606.257990,63797.102372,111706.813281,60472.524712,155039.495539,61393.797102,65488.378951,145689.359745,112229.596147,60990.232338
result.4686,1468.645099,582.163235,1468.644448,1468.645364,57244.249275,129254.428254,123281.984784,106553.163291,57214.807109,120355.005527,...,26917.067596,27009.418132,37647.403388,30084.949427,136420.244684,99942.128676,100804.373713,126897.886184,27430.958212,108937.128465
result.4687,1516.201688,511.258353,1516.201016,1516.202464,37276.825363,35638.598305,27610.984528,37541.052261,37149.384096,29078.814672,...,23327.894462,18576.931328,19362.108617,18843.872067,28083.117989,16835.686141,5501.967204,29795.652202,19987.232098,15951.412939
result.4688,1602.709281,504.401388,1602.708937,1602.709864,27442.557791,9772.502804,11429.535848,5957.559081,20620.731668,10957.582299,...,24901.089480,12316.132122,7674.670414,4277.872088,34846.682314,8724.857532,13243.195876,27555.954545,13780.790408,16870.720957

### Conduct data pre-processing using MetaMatching package
User can also have data pre-processing on other platform.

In [3]:
data_annos, matchings, sub_graph,  metabolites, dic = data_preprocessing(pos=pos, neg=neg, idx_feature = 4, match_tol_ppm=9, zero_threshold=0.75, scale = True)

The shape of data: (1174, 609)
The shape of feature-metabolites matching: (1174, 913)
The shape of metabolic network: (913, 913)

In [4]:
data_annos

,mz,time,min.mz,max.mz,B1_WU350.004_d7_polar_.mzML,B1_WU350.005_d14_polar_.mzML,B1_WU350.005_d7_polar_.mzML,B1_WU350.006_d14_polar_.mzML,B1_WU350.006_d3_polar_.mzML,B1_WU350.006_d7_polar_.mzML,...,B9_WU350.394_d7_polar_.mzML,B9_WU350.395_d0_polar_.mzML,B9_WU350.397_d0_polar_.mzML,B9_WU350.397_d3_polar_.mzML,B9_WU350.397_d7_polar_.mzML,B9_WU350.398_d0_polar_.mzML,B9_WU350.398_d3_polar_.mzML,B9_WU350.398_d7_polar_.mzML,B9_WU350.400_d0_polar_.mzML,B9_WU350.400_d3_polar_.mzML
pos.result.20,61.039522,196.416835,61.039471,61.039679,-0.263243,-0.178572,0.624692,0.242696,-0.422457,-0.176307,...,0.259012,-0.186812,0.099909,0.162074,0.714945,-0.373507,-0.208358,0.731144,-0.151466,-0.097045
pos.result.23,62.059713,120.385664,62.059579,62.059778,-1.466027,0.719099,-0.778658,0.044589,0.589671,0.562959,...,0.909980,0.556961,0.544209,-0.217913,-0.020393,0.092155,0.303131,0.238752,0.273281,-0.698148
pos.result.24,62.059773,567.364501,62.059573,62.059899,0.490957,0.605896,0.638400,0.532008,0.237163,0.614955,...,-0.342120,-0.491823,-0.161041,0.617654,0.591189,-0.235752,-0.472945,0.862268,-0.595044,0.283987
pos.result.27,63.043732,139.905082,63.043578,63.043941,-0.309131,-0.279996,0.777918,-0.061032,-0.599578,-0.697812,...,0.343829,-0.286160,-0.378739,-0.034057,0.480647,-0.130985,-0.027322,-0.409200,0.013918,-0.004305
pos.result.39,69.044108,142.410496,69.043938,69.044326,1.088133,0.602189,0.293277,0.352155,0.600051,0.196042,...,1.220960,0.069391,0.365372,1.220960,0.211665,0.067555,-0.112724,0.631074,1.220901,1.220901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
neg.result.2654,681.295731,64.941535,681.295422,681.295955,0.103765,-0.019746,-0.597129,0.282179,-0.801234,-0.807196,...,-0.287265,-0.309600,-0.324037,-0.386875,-0.446219,0.678076,-0.307214,-0.111083,-0.338571,-0.361127
neg.result.2774,973.314535,445.032143,973.313996,973.315277,-0.605257,-0.743090,-0.023999,-0.777730,-0.023402,-0.420732,...,-0.291901,-0.548229,0.666674,-0.273345,0.925437,0.259144,-0.521938,-0.081715,0.012205,0.958656
neg.result.2786,1018.317729,445.073482,1018.317337,1018.318266,-0.047428,0.064730,-0.917642,-0.221349,0.591571,0.316761,...,-0.363205,-0.224840,0.613736,0.099925,-0.081865,0.156956,-0.545020,0.052466,0.048001,0.275018
neg.result.2800,1040.298741,447.460359,1040.298282,1040.299241,0.840829,0.791141,-2.995697,2.466596,1.435598,1.214186,...,-2.995697,-2.995697,-2.995697,-2.995697,-2.995697,-2.995697,-2.995697,-2.995697,-2.995697,-2.995697
neg.result.2812,1092.268893,446.385231,1092.268244,1092.269543,2.933768,2.561341,1.143341,1.899126,2.102088,2.420282,...,-2.350033,-2.350033,-2.350033,-2.350033,-2.350033,-2.350033,-2.350033,-2.350033,-2.350033,-2.350033

In [5]:
# Y information
info = pd.read_csv("/home/keyan/phynn/knowledge_informed_ml/data/labels/y.csv")
info = info.iloc[np.where(np.logical_and(info['cov'] == 'Yes', info['icu'].isin(['Yes', 'No'])))[0], :]

# day0 test
# idx = np.where(info['day'] == 'd0')[0]
# info = info.iloc[idx, :]
# data_annos = data_annos.iloc[:, idx + 4]

# info = info.iloc[np.where(np.logical_and(info['cov'] == 'Yes', info['icu'].isin(['Yes', 'No'])))[0], :]

# idx_cov = np.where((info['cov'] == 'Yes'))[0]  #& (info['day']=='d0')
# # HUGE mistake!!!!
expression = (data_annos.iloc[:, 4:].T).values

print(expression.shape)

y = np.zeros(expression.shape[0])
y[np.where(info['icu'] == 'Yes')[0]] = 1  # change between cov/icu
print(y.shape)
target = y.astype(int)

(605, 1174)
(605,)

In [ ]:
maximum_step = 2 
# this is actually not the correct one, because we modify the first layer to be everything, so the true
# step is actually maximum_step + 1
num_hidden_layer_neuron_list = []
# target_keggids = np.random.choice(metaboliteDf['KEGGID'].values, 6, replace=False).tolist()
target_keggids = ['C00328', 'C00186', 'C00584', 'C02165', 'C00696', 
 'C01089', 'C00042', 'C06124', 'C00249', 'C00780']


# ['C00328', 'C00186', 'C00584', 'C02165', 'C00696', 
#  'C01089', 'C00042', 'C00026', 'C06124', 'C00249', 
#  'C00350', 'C00051', 'C00780', 'C00027']



#['C00186', 'C01089', 'C00164', 'C00249', 'C00712', 'C06124']
# 'C00078', 'C00328', 'C00123', 'C00584', 'C02165', 'C00158', 'C00042']



# ['C00029', 'C00032', 'C00036', 'C00041', 'C00042', 'C00047',
# 'C00048', 'C00049', 'C00052', 'C00058', 'C00059', 'C00061', 'C00062', 'C00064', 'C00163', 'C00189', 'C00246', 'C00292'
# 'C00334', 'C00388', 'C00519', 'C00546', 'C00555', 'C00580',
# 'C00804', 'C00937', 'C01026', 'C01205', 'C02218', 'C02659',
# 'C03284', 'C05145', 'C05670', 'C05999', 'C11735', 'C16310']

## Above are features from differenitial analysis
feature_meta = matchings
expression = expression
target = target
drop_out = 0.1
random_seed = 14526
batch_size = 16
lr = 1e-3
weight_decay = 0
num_epoch = 200

params, partition_mtx_dict, connectionList, acc_val = sparse_nn(expression=expression, labels=target, target_feature=target_keggids, feature_meta=feature_meta, knowledge_graph=sub_graph,random_seed=random_seed, maximum_step=maximum_step,
          num_hidden_layer_neuron_list=num_hidden_layer_neuron_list, drop_out=drop_out, batch_size=batch_size, lr=lr, weight_decay=weight_decay, num_epoch=num_epoch, abla_graph=False)

epoch: 1, test acc: 0.587912, train acc: 0.619385
epoch: 2, test acc: 0.587912, train acc: 0.619385
epoch: 3, test acc: 0.587912, train acc: 0.619385
epoch: 4, test acc: 0.587912, train acc: 0.619385
epoch: 5, test acc: 0.587912, train acc: 0.619385
epoch: 6, test acc: 0.587912, train acc: 0.619385
epoch: 7, test acc: 0.587912, train acc: 0.619385
epoch: 8, test acc: 0.587912, train acc: 0.619385
epoch: 9, test acc: 0.587912, train acc: 0.619385
epoch: 10, test acc: 0.587912, train acc: 0.619385
epoch: 11, test acc: 0.587912, train acc: 0.619385
epoch: 12, test acc: 0.587912, train acc: 0.619385
epoch: 13, test acc: 0.587912, train acc: 0.619385
epoch: 14, test acc: 0.587912, train acc: 0.619385
epoch: 15, test acc: 0.587912, train acc: 0.619385
epoch: 16, test acc: 0.587912, train acc: 0.619385
epoch: 17, test acc: 0.587912, train acc: 0.619385
epoch: 18, test acc: 0.587912, train acc: 0.619385
epoch: 19, test acc: 0.587912, train acc: 0.619385
epoch: 20, test acc: 0.587912, train acc: 0.619385
epoch: 21, test acc: 0.587912, train acc: 0.619385
epoch: 22, test acc: 0.587912, train acc: 0.619385
epoch: 23, test acc: 0.587912, train acc: 0.619385
epoch: 24, test acc: 0.587912, train acc: 0.619385
epoch: 25, test acc: 0.587912, train acc: 0.619385
epoch: 26, test acc: 0.587912, train acc: 0.619385
epoch: 27, test acc: 0.587912, train acc: 0.619385
epoch: 28, test acc: 0.587912, train acc: 0.619385
epoch: 29, test acc: 0.587912, train acc: 0.619385
epoch: 30, test acc: 0.587912, train acc: 0.619385
epoch: 31, test acc: 0.587912, train acc: 0.619385
epoch: 32, test acc: 0.587912, train acc: 0.619385
epoch: 33, test acc: 0.587912, train acc: 0.621749
epoch: 34, test acc: 0.587912, train acc: 0.621749
epoch: 35, test acc: 0.593407, train acc: 0.626478
epoch: 36, test acc: 0.593407, train acc: 0.626478
epoch: 37, test acc: 0.593407, train acc: 0.638298
epoch: 38, test acc: 0.615385, train acc: 0.650118
epoch: 39, test acc: 0.615385, train acc: 0.676123
epoch: 40, test acc: 0.620879, train acc: 0.683215
epoch: 41, test acc: 0.631868, train acc: 0.683215
epoch: 42, test acc: 0.631868, train acc: 0.716312
epoch: 43, test acc: 0.615385, train acc: 0.718676
epoch: 44, test acc: 0.637363, train acc: 0.728132
epoch: 45, test acc: 0.659341, train acc: 0.751773
epoch: 46, test acc: 0.653846, train acc: 0.761229
epoch: 47, test acc: 0.648352, train acc: 0.770686
epoch: 48, test acc: 0.648352, train acc: 0.773050
epoch: 49, test acc: 0.659341, train acc: 0.770686
epoch: 50, test acc: 0.648352, train acc: 0.773050
epoch: 51, test acc: 0.642857, train acc: 0.782506
epoch: 52, test acc: 0.648352, train acc: 0.777778
epoch: 53, test acc: 0.637363, train acc: 0.782506
epoch: 54, test acc: 0.637363, train acc: 0.775414
epoch: 55, test acc: 0.631868, train acc: 0.796690
epoch: 56, test acc: 0.637363, train acc: 0.796690
epoch: 57, test acc: 0.631868, train acc: 0.796690
epoch: 58, test acc: 0.631868, train acc: 0.799054
epoch: 59, test acc: 0.631868, train acc: 0.789598
epoch: 60, test acc: 0.653846, train acc: 0.810875
epoch: 61, test acc: 0.653846, train acc: 0.822695
epoch: 62, test acc: 0.626374, train acc: 0.794326
epoch: 63, test acc: 0.659341, train acc: 0.827423
epoch: 64, test acc: 0.659341, train acc: 0.839243
epoch: 65, test acc: 0.642857, train acc: 0.836879
epoch: 66, test acc: 0.675824, train acc: 0.832151
epoch: 67, test acc: 0.659341, train acc: 0.853428
epoch: 68, test acc: 0.648352, train acc: 0.841608
epoch: 69, test acc: 0.686813, train acc: 0.851064
epoch: 70, test acc: 0.686813, train acc: 0.858156
epoch: 71, test acc: 0.675824, train acc: 0.865248
epoch: 72, test acc: 0.697802, train acc: 0.855792
epoch: 73, test acc: 0.675824, train acc: 0.865248
epoch: 74, test acc: 0.686813, train acc: 0.872340
epoch: 75, test acc: 0.686813, train acc: 0.877069
epoch: 76, test acc: 0.692308, train acc: 0.872340
epoch: 77, test acc: 0.675824, train acc: 0.879433
epoch: 78, test acc: 0.703297, train acc: 0.874704
epoch: 79, test acc: 0.697802, train acc: 0.886525
epoch: 80, test acc: 0.697802, train acc: 0.881797
epoch: 81, test acc: 0.708791, train acc: 0.879433
epoch: 82, test acc: 0.697802, train acc: 0.872340
epoch: 83, test acc: 0.703297, train acc: 0.884161
epoch: 84, test acc: 0.708791, train acc: 0.893617
epoch: 85, test acc: 0.708791, train acc: 0.893617
epoch: 86, test acc: 0.703297, train acc: 0.893617
epoch: 87, test acc: 0.708791, train acc: 0.900709
epoch: 88, test acc: 0.714286, train acc: 0.891253
epoch: 89, test acc: 0.703297, train acc: 0.907801
epoch: 90, test acc: 0.703297, train acc: 0.919622
epoch: 91, test acc: 0.703297, train acc: 0.914894
epoch: 92, test acc: 0.703297, train acc: 0.924350
epoch: 93, test acc: 0.714286, train acc: 0.919622
epoch: 94, test acc: 0.708791, train acc: 0.917258
epoch: 95, test acc: 0.697802, train acc: 0.919622
epoch: 96, test acc: 0.708791, train acc: 0.926714
epoch: 97, test acc: 0.703297, train acc: 0.926714
epoch: 98, test acc: 0.703297, train acc: 0.926714
epoch: 99, test acc: 0.708791, train acc: 0.929078
epoch: 100, test acc: 0.714286, train acc: 0.926714
epoch: 101, test acc: 0.708791, train acc: 0.931442
epoch: 102, test acc: 0.708791, train acc: 0.931442
epoch: 103, test acc: 0.697802, train acc: 0.933806
epoch: 104, test acc: 0.708791, train acc: 0.938534
epoch: 105, test acc: 0.697802, train acc: 0.933806
epoch: 106, test acc: 0.708791, train acc: 0.938534
epoch: 107, test acc: 0.714286, train acc: 0.943262
epoch: 108, test acc: 0.703297, train acc: 0.938534
epoch: 109, test acc: 0.708791, train acc: 0.943262
epoch: 110, test acc: 0.708791, train acc: 0.940898
epoch: 111, test acc: 0.697802, train acc: 0.929078
epoch: 112, test acc: 0.708791, train acc: 0.943262
epoch: 113, test acc: 0.708791, train acc: 0.940898
epoch: 114, test acc: 0.714286, train acc: 0.943262
epoch: 115, test acc: 0.708791, train acc: 0.945626
epoch: 116, test acc: 0.714286, train acc: 0.943262
epoch: 117, test acc: 0.703297, train acc: 0.943262
epoch: 118, test acc: 0.714286, train acc: 0.947991
epoch: 119, test acc: 0.703297, train acc: 0.943262
epoch: 120, test acc: 0.708791, train acc: 0.943262
epoch: 121, test acc: 0.708791, train acc: 0.938534
epoch: 122, test acc: 0.725275, train acc: 0.945626
epoch: 123, test acc: 0.708791, train acc: 0.947991
epoch: 124, test acc: 0.708791, train acc: 0.950355
epoch: 125, test acc: 0.708791, train acc: 0.950355
epoch: 126, test acc: 0.708791, train acc: 0.955083
epoch: 127, test acc: 0.714286, train acc: 0.955083
epoch: 128, test acc: 0.708791, train acc: 0.955083
epoch: 129, test acc: 0.703297, train acc: 0.955083
epoch: 130, test acc: 0.703297, train acc: 0.957447
epoch: 131, test acc: 0.714286, train acc: 0.957447
epoch: 132, test acc: 0.703297, train acc: 0.955083
epoch: 133, test acc: 0.708791, train acc: 0.947991
epoch: 134, test acc: 0.708791, train acc: 0.957447
epoch: 135, test acc: 0.714286, train acc: 0.959811
epoch: 136, test acc: 0.708791, train acc: 0.959811
epoch: 137, test acc: 0.703297, train acc: 0.959811
epoch: 138, test acc: 0.708791, train acc: 0.959811
epoch: 139, test acc: 0.708791, train acc: 0.959811
epoch: 140, test acc: 0.708791, train acc: 0.959811
epoch: 141, test acc: 0.719780, train acc: 0.962175
epoch: 142, test acc: 0.714286, train acc: 0.962175
epoch: 143, test acc: 0.692308, train acc: 0.962175
epoch: 144, test acc: 0.719780, train acc: 0.962175
epoch: 145, test acc: 0.703297, train acc: 0.962175
epoch: 146, test acc: 0.692308, train acc: 0.962175
epoch: 147, test acc: 0.697802, train acc: 0.962175
epoch: 148, test acc: 0.714286, train acc: 0.962175
epoch: 149, test acc: 0.708791, train acc: 0.962175
epoch: 150, test acc: 0.703297, train acc: 0.962175
epoch: 151, test acc: 0.703297, train acc: 0.962175
epoch: 152, test acc: 0.697802, train acc: 0.962175
epoch: 153, test acc: 0.703297, train acc: 0.962175
epoch: 154, test acc: 0.703297, train acc: 0.962175
epoch: 155, test acc: 0.703297, train acc: 0.962175
epoch: 156, test acc: 0.708791, train acc: 0.962175
epoch: 157, test acc: 0.703297, train acc: 0.962175
epoch: 158, test acc: 0.703297, train acc: 0.962175
epoch: 159, test acc: 0.697802, train acc: 0.962175
epoch: 160, test acc: 0.714286, train acc: 0.962175
epoch: 161, test acc: 0.708791, train acc: 0.962175
epoch: 162, test acc: 0.708791, train acc: 0.962175
epoch: 163, test acc: 0.697802, train acc: 0.962175
epoch: 164, test acc: 0.703297, train acc: 0.962175
epoch: 165, test acc: 0.703297, train acc: 0.962175
epoch: 166, test acc: 0.708791, train acc: 0.962175
epoch: 167, test acc: 0.708791, train acc: 0.962175
epoch: 168, test acc: 0.714286, train acc: 0.962175
epoch: 169, test acc: 0.708791, train acc: 0.962175
epoch: 170, test acc: 0.708791, train acc: 0.962175
epoch: 171, test acc: 0.719780, train acc: 0.962175
epoch: 172, test acc: 0.697802, train acc: 0.962175
epoch: 173, test acc: 0.708791, train acc: 0.962175
epoch: 174, test acc: 0.714286, train acc: 0.964539
epoch: 175, test acc: 0.714286, train acc: 0.964539
epoch: 176, test acc: 0.703297, train acc: 0.964539
epoch: 177, test acc: 0.714286, train acc: 0.966903
epoch: 178, test acc: 0.714286, train acc: 0.966903
epoch: 179, test acc: 0.703297, train acc: 0.966903
epoch: 180, test acc: 0.708791, train acc: 0.966903
epoch: 181, test acc: 0.708791, train acc: 0.966903
epoch: 182, test acc: 0.708791, train acc: 0.966903
epoch: 183, test acc: 0.714286, train acc: 0.969267
epoch: 184, test acc: 0.708791, train acc: 0.969267
epoch: 185, test acc: 0.714286, train acc: 0.969267
epoch: 186, test acc: 0.708791, train acc: 0.969267
epoch: 187, test acc: 0.708791, train acc: 0.969267
epoch: 188, test acc: 0.708791, train acc: 0.969267
epoch: 189, test acc: 0.708791, train acc: 0.969267
epoch: 190, test acc: 0.708791, train acc: 0.969267
epoch: 191, test acc: 0.708791, train acc: 0.969267
epoch: 192, test acc: 0.708791, train acc: 0.969267
epoch: 193, test acc: 0.714286, train acc: 0.969267
epoch: 194, test acc: 0.708791, train acc: 0.969267
epoch: 195, test acc: 0.708791, train acc: 0.969267
epoch: 196, test acc: 0.714286, train acc: 0.969267
epoch: 197, test acc: 0.708791, train acc: 0.969267
epoch: 198, test acc: 0.714286, train acc: 0.969267
epoch: 199, test acc: 0.708791, train acc: 0.969267
epoch: 200, test acc: 0.714286, train acc: 0.969267

ValueError: too many values to unpack (expected 3)

In [ ]:
def save_param(model, connectionlist,
               path=f'/home/keyan/phynn/knowledge_informed_ml/result/metaparams_{random_seed}.npz'):
    np.savez_compressed(path,
        model_params=model,
        connectionlist={str(k):v for k,v in enumerate(connectionlist)}
                        )
    return

In [ ]:
# save_param(model, connectionList)